[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.25"
evm_version = "cancun"
ffi = true
fs_permissions = [
    { access = "read-write", path = ".forge-snapshots/" },
    { access = "read", path = "./broadcast" },
]

[fuzz]
runs = 1000

[invariant]
fail_on_revert = false
runs = 1000
depth = 25
